version: '3.3'
services:
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  web:
    #image: php:7.2.2-apache
    build: PHP
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "8100:80"
    #stdin_open: true
    #tty: true

# Names our volume
volumes:
  my-db: